version: '3.9'



services:


  db:
    image: postgres:14.3-alpine3.15
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_HOST: ${PG_HOST}




  web:
    build: ./app
    command: gunicorn -b 0.0.0.0:5000 app:app --capture-output
# при редактировании папки app изменения отражаются в контейнере
#    volumes:
#      - ./app/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db



volumes:
  postgres_data:

